### ISSUE TITLE
Media hinzufügen wirft FileNotFoundException

### ISSUE THREAD

**Issue by Jerry0022** [JFARM2016/ProjectHungry#12]
Wenn man ein Bild schießt und danach ein Media updated, kommt immer dieser Fehler. Bitte E2E beheben.

`E/StepsAdapter: Database not found!
                                                        java.io.FileNotFoundException: file:/data/data/eu.eatable/files/images/Foto.jpg: open failed: ENOENT (No such file or directory)
                                                            at libcore.io.IoBridge.open(IoBridge.java:456)
                                                            at java.io.FileInputStream.<init>(FileInputStream.java:76)
                                                            at java.io.FileInputStream.<init>(FileInputStream.java:103)
                                                            at eu.eatable.persistence.Media.readContent(Media.java:120)
                                                            at eu.eatable.persistence.DAO.updateEatable(DAO.java:304)
                                                            at eu.eatable.cc.steps.StepsAdapter.addMediaToStep(StepsAdapter.java:228)
                                                            at eu.eatable.cc.steps.StepsAdapter$ViewHolder$4.onDrag(StepsAdapter.java:467)
                                                            at android.view.View.dispatchDragEvent(View.java:19773)
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1409)
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395)
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395)
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395)
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395)
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395)
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395)
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395)
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395)
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395)
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395)
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395)
                                                            at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:6115)
                                                            at android.view.ViewRootImpl.access$900(ViewRootImpl.java:178)
                                                            at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4004)
                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                            at android.os.Looper.loop(Looper.java:145)
                                                            at android.app.ActivityThread.main(ActivityThread.java:6872)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
                                                         Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                            at libcore.io.Posix.open(Native Method)
                                                            at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                            at libcore.io.IoBridge.open(IoBridge.java:442)
                                                            at java.io.FileInputStream.<init>(FileInputStream.java:76) 
                                                            at java.io.FileInputStream.<init>(FileInputStream.java:103) 
                                                            at eu.eatable.persistence.Media.readContent(Media.java:120) 
                                                            at eu.eatable.persistence.DAO.updateEatable(DAO.java:304) 
                                                            at eu.eatable.cc.steps.StepsAdapter.addMediaToStep(StepsAdapter.java:228) 
                                                            at eu.eatable.cc.steps.StepsAdapter$ViewHolder$4.onDrag(StepsAdapter.java:467) 
                                                            at android.view.View.dispatchDragEvent(View.java:19773) 
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1409) 
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395) 
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395) 
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395) 
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395) 
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395) 
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395) 
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395) 
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395) 
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395) 
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395) 
                                                            at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1395) 
                                                            at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:6115) 
                                                            at android.view.ViewRootImpl.access$900(ViewRootImpl.java:178) 
                                                            at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4004) 
                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                            at android.os.Looper.loop(Looper.java:145) 
                                                            at android.app.ActivityThread.main(ActivityThread.java:6872) 
                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) `

**Comment by spike-rabbit** [comment]
lag am dem Falschen übersetzten der Uri zum Pfad
