### ISSUE TITLE
ReadEatable() funktioniert nicht

### ISSUE THREAD

**Issue by FloriVonDerGPC** [JFARM2016/ProjectHungry#13]
Wenn im HomeScreen shortEatable angeklickt wird, beendet sich die App mit folgender Fehlermeldung:

`FATAL EXCEPTION: main
                                                          Process: eu.eatable, PID: 3207
                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.eatable/eu.eatable.DetailActivity}: java.lang.ClassCastException: java.lang.Integer cannot be cast to eu.eatable.persistence.Field
                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                              at android.os.Looper.loop(Looper.java:148)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                           Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to eu.eatable.persistence.Field
                                                              at eu.eatable.detail.DetailListAdapter.<init>(DetailListAdapter.java:42)
                                                              at eu.eatable.DetailActivity.onCreate(DetailActivity.java:43)
                                                              at android.app.Activity.performCreate(Activity.java:6237)
                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                              at android.os.Looper.loop(Looper.java:148) 
                                                              at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                              at java.lang.reflect.Method.invoke(Native Method)`

**Comment by spike-rabbit** [comment]
das problem liegt irgendwo beim Parceln. Aus irgendeinem Grund liest er Integerwerte ein, obwohl es eigentlich fields sind.

**Comment by spike-rabbit** [comment]
solved by saving fields as serializable
