### ISSUE TITLE
Nullpointer in DetailListAdapter

### ISSUE THREAD

**Issue by spike-rabbit** [JFARM2016/ProjectHungry#17]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
                                                              at eu.eatable.detail.DetailListAdapter$ViewHolder.<init>(DetailListAdapter.java:134)
                                                              at eu.eatable.detail.DetailListAdapter.onCreateViewHolder(DetailListAdapter.java:89)
                                                              at eu.eatable.detail.DetailListAdapter.onCreateViewHolder(DetailListAdapter.java:40)
                                                              at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5482)
                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4707)
                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
                                                              at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
                                                              at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
                                                              at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                              at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
                                                              at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
                                                              at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2625)
                                                              at android.view.View.measure(View.java:17430)
                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
                                                              at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:668)
                                                              at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:735)
                                                              at android.view.View.measure(View.java:17430)
                                                              at android.widget.RelativeLayout.measureChild(RelativeLayout.java:697)
                                                              at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
                                                              at android.view.View.measure(View.java:17430)
                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                              at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                              at android.view.View.measure(View.java:17430)
                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
                                                              at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                              at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                              at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                              at android.view.View.measure(View.java:17430)
                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                              at android.view.View.measure(View.java:17430)
                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
                                                              at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                              at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                              at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                              at android.view.View.measure(View.java:17430)
                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                              at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2560)
                                                              at android.view.View.measure(View.java:17430)
                                                              at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2001)
                                                              at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1166)
                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1372)
                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                              at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at android.os.Looper.loop(Looper.java:135)
                                                          	at android.app.ActivityThread.main(ActivityThread

**Comment by Jerry0022** [comment]
Kann ich nicht nachvollziehen, erst muss #

**Comment by Jerry0022** [comment]
fixed
