### ISSUE TITLE
Dateien funktionieren nicht

### ISSUE THREAD

**Issue by Jerry0022** [JFARM2016/ProjectHungry#29]
Ursache DAO:

FATAL EXCEPTION: pool-2-thread-2
                                                            Process: eu.eatable, PID: 26567
                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
                                                                at eu.eatable.persistence.DAO$EatableWriter.run(DAO.java:418)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                at java.lang.Thread.run(Thread.java:818)

**Comment by Jerry0022** [comment]
Siehe #7
